# Generated by Django 4.0.1 on 2022-01-31 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BascektShop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingbasket',
            name='basket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='BascektShop.finalbasket'),
        ),
    ]
